image:
- Visual Studio 2019
clone_folder: C:\project\BasicChatClient
build_script:
- cmd: >-
    mkdir bin

    cd bin
    
    cmake C:\project\BasicChatClient -G "Visual Studio 16 2019"
    
    cmake --build .

    cmake --build . --config Release
    
    cmake --build . --config Debug

    cd C:\project\BasicChatClient\src\tests

    python tracker.py